name 'chef_iis'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_iis'
long_description 'Installs/Configures chef_iis'
version '0.1.0'
